package wosec.server.model;

// Generated 16.08.2011 03:37:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ActivityTypes generated by hbm2java
 */
public class ActivityType implements java.io.Serializable {

	private Integer typeId;
	private String name;
	private Set<Activity> activities = new HashSet<Activity>(0);
	private Set<Event> events = new HashSet<Event>(0);

	public ActivityType() {
	}

	public ActivityType(int typeId, String name) {
		this.typeId = typeId;
		this.name = name;
	}

	public ActivityType(int typeId, String name, Set<Activity> activities,
			Set events, Set activityGroups) {
		this.typeId = typeId;
		this.name = name;
		this.activities = activities;
		this.events = events;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}
}
