package wosec.server.model;

// Generated 21.08.2011 18:54:31 by Hibernate Tools 3.4.0.CR1
import java.util.HashSet;
import java.util.Set;

/**
 * Activities generated by hbm2java
 */
public class Activity implements java.io.Serializable {

    private ActivityId id;
    private Activity groupActivity;
    private Workflow workflow;
    private Activity refActivity;
    private byte isGroup;
    private ActivityInformation activityInformation;
    private Set<EventInformation> eventInformations = new HashSet(0);
    private Set<Activity> destActivities = new HashSet<Activity>();
    private Set<ActivityType> activityTypes = new HashSet<ActivityType>(0);
    private Set<Activity> refActivities = new HashSet<Activity>(0);
    private Set<Activity> groupIds = new HashSet<Activity>(0);

    public Activity() {
    }

    public Activity(ActivityId id,
            Set<Activity> destActivities,
            Activity groupActivity,
            Workflow workflow,
            Activity refActivity, byte isGroup) {
        this.id = id;
        this.destActivities = destActivities;
        this.groupActivity = groupActivity;
        this.workflow = workflow;
        this.refActivity = refActivity;
        this.isGroup = isGroup;
    }

    public Activity(ActivityId id,
            Activity groupActivity,
            Workflow workflow,
            Activity refActivity, byte isGroup,
            ActivityInformation activityInformation, Set<EventInformation> eventInformation,
            Set<ActivityType> activityTypes, Set<Activity> refActivities,
            Set<Activity> groupIds) {
        this.id = id;
        this.groupActivity = groupActivity;
        this.workflow = workflow;
        this.refActivity = refActivity;
        this.isGroup = isGroup;
        this.activityInformation = activityInformation;
        this.eventInformations = eventInformation;
        this.activityTypes = activityTypes;
        this.refActivities = refActivities;
        this.groupIds = groupIds;
    }

    public ActivityId getId() {
        return this.id;
    }

    public void setId(ActivityId id) {
        this.id = id;
    }

    public Set<Activity> getDestActivities() {
        return destActivities;
    }

    public void setDestActivities(Set<Activity> destActivities) {
        this.destActivities = destActivities;
    }

    public Activity getGroupActivity() {
        return this.groupActivity;
    }

    public void setGroupActivity(Activity groupActivity) {
        this.groupActivity = groupActivity;
    }

    public Workflow getWorkflow() {
        return this.workflow;
    }

    public void setWorkflow(Workflow workflow) {
        this.workflow = workflow;
    }

    public Activity getRefActivity() {
        return this.refActivity;
    }

    public void setRefActivity(Activity refActivity) {
        this.refActivity = refActivity;
    }

    public byte getIsGroup() {
        return this.isGroup;
    }

    public void setIsGroup(byte isGroup) {
        this.isGroup = isGroup;
    }

    public ActivityInformation getActivityInformation() {
        return this.activityInformation;
    }

    public void setActivityInformation(ActivityInformation activityInformation) {
        this.activityInformation = activityInformation;
    }

    public Set getEventInformation() {
        return this.eventInformations;
    }

    public void setEventInformation(Set eventInformation) {
        this.eventInformations = eventInformation;
    }

    public Set<ActivityType> getActivityTypes() {
        return activityTypes;
    }

    public void setActivityTypes(Set<ActivityType> activityTypes) {
        this.activityTypes = activityTypes;
    }

    public Set<EventInformation> getEventInformations() {
        return eventInformations;
    }

    public void setEventInformations(Set<EventInformation> eventInformations) {
        this.eventInformations = eventInformations;
    }

    public Set<Activity> getGroupIds() {
        return groupIds;
    }

    public void setGroupIds(Set<Activity> groupIds) {
        this.groupIds = groupIds;
    }

    public Set<Activity> getRefActivities() {
        return refActivities;
    }

    public void setRefActivities(Set<Activity> refActivities) {
        this.refActivities = refActivities;
    }
}
