package wosec.server.model;

// Generated 21.08.2011 18:54:31 by Hibernate Tools 3.4.0.CR1
/**
 * ActivitiesId generated by hbm2java
 */
public class ActivityId implements java.io.Serializable {

    private String activityId;
    private String workflowId;

    public ActivityId() {
    }

    public ActivityId(String activityId, String workflowId) {
        this.activityId = activityId;
        this.workflowId = workflowId;
    }

    public String getActivityId() {
        return this.activityId;
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    public String getWorkflowId() {
        return this.workflowId;
    }

    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ActivityId)) {
            return false;
        }
        ActivityId castOther = (ActivityId) other;

        return ((this.getActivityId() == null ? castOther.getActivityId() == null : this.getActivityId().equals(castOther.getActivityId())) || (this.getActivityId() != null && castOther.getActivityId() != null && this.getActivityId().equals(castOther.getActivityId())))
                && ((this.getWorkflowId() == null ? castOther.getWorkflowId() == null : this.getWorkflowId().equals(castOther.getWorkflowId())) || (this.getWorkflowId() != null
                && castOther.getWorkflowId() != null && this.getWorkflowId().equals(castOther.getWorkflowId())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getActivityId() == null ? 0 : this.getActivityId().hashCode());
        result = 37
                * result
                + (getWorkflowId() == null ? 0 : this.getWorkflowId().hashCode());
        return result;
    }
}
