package wosec.server.model;

// Generated 16.08.2011 03:37:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DataProvider generated by hbm2java
 */
public class DataProvider implements java.io.Serializable {

	private Integer id;
	private Workflow workflow;
	private String name;
	private Set<EventInformation> eventInformations = new HashSet<EventInformation>(0);

	public DataProvider() {
	}

	public DataProvider(Integer id, Workflow workflow, String name) {
		this.id = id;
		this.workflow = workflow;
		this.name = name;
	}

	public DataProvider(Integer id, Workflow workflow, String name,
			Set<EventInformation> eventInformation) {
		this.id = id;
		this.workflow = workflow;
		this.name = name;
		this.eventInformations = eventInformation;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Workflow getWorkflow() {
		return this.workflow;
	}

	public void setWorkflow(Workflow workflow) {
		this.workflow = workflow;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<EventInformation> getEventInformations() {
		return this.eventInformations;
	}

	public void setEventInformations(Set<EventInformation> eventInformation) {
		this.eventInformations = eventInformation;
	}

}
