package wosec.server.model;

// Generated 21.08.2011 18:54:31 by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * EventInformation generated by hbm2java
 */
public class EventInformation implements java.io.Serializable {

    private EventId id;
    private User executingUser;
    private Event event;
    private DataProvider dataProvider;
    private User evokingUser;
    private Date eventTime;
    private Activity activity;
    private Activity fromActivity;
    private EventData eventData;

    public EventInformation() {
    }

    public EventInformation(Event event, Date eventTime) {
        this.event = event;
        this.eventTime = eventTime;
    }

    public EventInformation(User usersByExecutingUser, Event event,
            DataProvider dataProvider, User usersByEvokingUser, Activity fromActivity,
            Date eventTime, Activity activity, EventData eventData) {
        this.executingUser = usersByExecutingUser;
        this.event = event;
        this.dataProvider = dataProvider;
        this.evokingUser = usersByEvokingUser;
        this.eventTime = eventTime;
        this.fromActivity = fromActivity;
        this.activity = activity;
        this.eventData = eventData;
    }

    public EventId getId() {
        return this.id;
    }

    public void setId(EventId id) {
        this.id = id;
    }

    public Event getEvent() {
        return event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }

    public DataProvider getDataProvider() {
        return this.dataProvider;
    }

    public void setDataProvider(DataProvider dataProvider) {
        this.dataProvider = dataProvider;
    }

    public User getEvokingUser() {
        return evokingUser;
    }

    public User getExecutingUser() {
        return executingUser;
    }

    public void setEvokingUser(User evokingUser) {
        this.evokingUser = evokingUser;
    }

    public void setExecutingUser(User executingUser) {
        this.executingUser = executingUser;
    }

    public Date getEventTime() {
        return this.eventTime;
    }

    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }

    public Activity getActivity() {
        return activity;
    }

    public void setActivity(Activity activity) {
        this.activity = activity;
    }

    public Activity getFromActivity() {
        return fromActivity;
    }

    public void setFromActivity(Activity fromActivity) {
        this.fromActivity = fromActivity;
    }

    public EventData getEventData() {
        return this.eventData;
    }

    public void setEventData(EventData eventData) {
        this.eventData = eventData;
    }
}
