package wosec.server.model;

// Generated 21.08.2011 18:54:31 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * EventAttachments generated by hbm2java
 */
public class EventAttachment implements java.io.Serializable {

	private Integer attachmentId;
	private String name;
	private String attachmentType;
	private Serializable attachment;
	private Set<EventData> eventDatas = new HashSet<EventData>(0);

	public EventAttachment() {
	}

	public EventAttachment(String name, String attachmentType,
			Serializable attachment) {
		this.name = name;
		this.attachmentType = attachmentType;
		this.attachment = attachment;
	}

	public EventAttachment(String name, String attachmentType,
			Serializable attachment, Set<EventData> eventDatas) {
		this.name = name;
		this.attachmentType = attachmentType;
		this.attachment = attachment;
		this.eventDatas = eventDatas;
	}

	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAttachmentType() {
		return this.attachmentType;
	}

	public void setAttachmentType(String attachmentType) {
		this.attachmentType = attachmentType;
	}

	public Serializable getAttachment() {
		return this.attachment;
	}

	public void setAttachment(Serializable attachment) {
		this.attachment = attachment;
	}

	public Set<EventData> getEventDatas() {
		return this.eventDatas;
	}

	public void setEventDatas(Set<EventData> eventDatas) {
		this.eventDatas = eventDatas;
	}

}
