package wosec.server.model;

// Generated 21.08.2011 18:54:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EventData generated by hbm2java
 */
public class EventData implements java.io.Serializable {

	private EventId id;
	private EventInformation eventInformation;
	private String dataUsed;
	private String usageReason;
	private Set eventAttachments = new HashSet(0);

	public EventData() {
	}

	public EventData(EventInformation eventInformation, String dataUsed,
			String usageReason) {
		this.eventInformation = eventInformation;
		this.dataUsed = dataUsed;
		this.usageReason = usageReason;
	}

	public EventData(EventInformation eventInformation, String dataUsed,
			String usageReason, Set eventAttachmentses) {
		this.eventInformation = eventInformation;
		this.dataUsed = dataUsed;
		this.usageReason = usageReason;
		this.eventAttachments = eventAttachmentses;
	}

	public EventId getId() {
		return this.id;
	}

	public void setId(EventId id) {
		this.id = id;
	}

	public EventInformation getEventInformation() {
		return this.eventInformation;
	}

	public void setEventInformation(EventInformation eventInformation) {
		this.eventInformation = eventInformation;
	}

	public String getDataUsed() {
		return this.dataUsed;
	}

	public void setDataUsed(String dataUsed) {
		this.dataUsed = dataUsed;
	}

	public String getUsageReason() {
		return this.usageReason;
	}

	public void setUsageReason(String usageReason) {
		this.usageReason = usageReason;
	}

	public Set getEventAttachments() {
		return this.eventAttachments;
	}

	public void setEventAttachments(Set eventAttachments) {
		this.eventAttachments = eventAttachments;
	}

}
