package wosec.server.model;

// Generated 16.08.2011 03:37:48 by Hibernate Tools 3.4.0.CR1
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * UserRoles generated by hbm2java
 */
public class UserRole implements Serializable {

    public static final String ROLE_USER = "User";
    public static final String ROLE_BPMN = "BPMN-Designer";
    public static final String ROLE_ADMN = "Administrator";
    public static final String ROLE_APP = "Application";
    private Integer roleId;
    private String name;
    private Set<User> users = new HashSet<User>(0);

    public UserRole() {
    }

    public UserRole(String name) {
        this.name = name;
    }

    public UserRole(String name, Set<User> users) {
        this.name = name;
        this.users = users;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }
}