package wosec.server.model;

// Generated 16.08.2011 03:37:48 by Hibernate Tools 3.4.0.CR1
/**
 * WorkflowLanguages generated by hbm2java
 */
public class WorkflowLanguage implements java.io.Serializable {

    private WorkflowLanguageId id;
    private Workflow workflow;
    private byte isDefault;

    public WorkflowLanguage() {
    }

    public WorkflowLanguage(WorkflowLanguageId id, Workflow workflow, byte isDefault) {
        this.id = id;
        this.workflow = workflow;
        this.isDefault = isDefault;
    }

    public WorkflowLanguageId getId() {
        return this.id;
    }

    public void setId(WorkflowLanguageId id) {
        this.id = id;
    }

    public Workflow getWorkflow() {
        return this.workflow;
    }

    public void setWorkflow(Workflow workflow) {
        this.workflow = workflow;
    }

    public byte getIsDefault() {
        return this.isDefault;
    }

    public void setIsDefault(byte isDefault) {
        this.isDefault = isDefault;
    }
}
