package wosec.server.model;

// Generated 16.08.2011 03:37:48 by Hibernate Tools 3.4.0.CR1
/**
 * WorkflowLanguagesId generated by hbm2java
 */
public class WorkflowLanguageId implements java.io.Serializable {

    private String workflowId;
    private String language;

    public WorkflowLanguageId() {
    }

    public WorkflowLanguageId(String workflowId, String language) {
        this.workflowId = workflowId;
        this.language = language;
    }

    public String getWorkflowId() {
        return this.workflowId;
    }

    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof WorkflowLanguageId)) {
            return false;
        }
        WorkflowLanguageId castOther = (WorkflowLanguageId) other;

        return (this.getWorkflowId() == castOther.getWorkflowId())
                && ((this.getLanguage().equals(castOther.getLanguage())) || (this.getLanguage() != null
                && castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getWorkflowId() == null ? 0 : this.getWorkflowId().hashCode());
        result = 37 * result
                + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
        return result;
    }
}
